# Site settings
title: "Farrell Lab @ NICHD"
description: > 
  Write a description of your website here.

author: Jeffrey Farrell
email: jeffrey.farrell@nih.gov
twitter_username: JeffreyAFarrell
github_username: farrelllab

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://farrelllab.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

